pglookout: Fix stats emission when we're an observer, fixes #31
emit_stats() is broken for observers since they have no state of their
own to emit as stats. This would cause an exception like:

AttributeError: 'NoneType' object has no attribute 'get' from emit_stats